# Quarkus application configuration

# Do not only listen on localhost
%dev.quarkus.http.host=0.0.0.0

# Set context path for the application
quarkus.http.root-path=/maarten-monolith/api
%test.quarkus.http.root-path=/

# Application info
quarkus.application.name=maarten-monolith
